version: "3"

vars:
  FASTLANE: "bundle exec fastlane"

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  install:
    cmds:
      - bundle install
  test:
    cmds:
      - "{{.FASTLANE}} test"
    deps:
      - install
