# https://taskfile.dev

version: "3"

vars:
  FASTLANE: bundle exec fastlane

tasks:
  default:
    cmds:
      - task --list
    silent: true

  install:
    desc: "Install dependencies"
    cmds:
      - "bundle install"

  test:
    desc: "Run tests"
    cmds:
      - "{{.FASTLANE}} test"
